import type { Metadata } from "next";

import { Inter } from "next/font/google";
import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Google font Inter
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased text-font-primary bg-workspace-primary scroll-smooth`}>
        <Navbar />
        <div className="p-4 sm:p-6 md:p-8 lg:p-10">{children}</div>
      </body>
    </html>
  );
}
